server:
  port: 8003
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.pzf.springcloud.entities        # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
      name: MicroServiceCloud-dept                            #Spring对外暴露的微服务名字
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
      url: jdbc:mysql://localhost:3306/cloudDB03?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: admin1004
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取的最大超时时间


eureka:
  client:     #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: MicroServiceCloud-dept8003   #注册到Eureka中的实例的别名（自定义服务名称）
    prefer-ip-address: true   #访问路径可以显示IP地址

info:
  app.name: pzf-MicroServiceCloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  
  
  
  